// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductStockApi.Db;

#nullable disable

namespace ProductStockApi.Migrations
{
    [DbContext(typeof(ProductStockContext))]
    [Migration("20220828142710_edit_model")]
    partial class edit_model
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductStockApi.Models.ProductStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productStock_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("NewAddedProductCount")
                        .HasColumnType("int")
                        .HasColumnName("productStock_newAddedProductCount");

                    b.Property<int>("NewSoldProductCount")
                        .HasColumnType("int")
                        .HasColumnName("productStock_newSoldProductCount");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productStock_name");

                    b.Property<int>("StockCount")
                        .HasColumnType("int")
                        .HasColumnName("productStock_stockCount");

                    b.HasKey("Id");

                    b.ToTable("ProductStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
